### PR TITLE
Update train.py for newer versions of TensorFlow

### PR DESCRIPTION
**Pull request by Ressnn**
Epochs argument must be int for never versions of TensorFlow.

### CODE REVIEW

**Comment by Ressnn** [comment]
Also had to make some changes to plot.py to get code to work for me. This may also be a TensorFlow version issue.

**Comment by KonradLinkowski** [comment]
Seems fine to me

**Comment by Ressnn** [comment]
Maybe it's just my setup.

**Comment by KonradLinkowski** [comment]
@Ressnn I mean, your solution was ok. You can reopen this so I will merge this

**Pull request merged**
